# Local 프로파일 설정 (개발자 로컬 환경 - H2 인메모리 DB)
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/testdb;MODE=MySQL;AUTO_SERVER=TRUE
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    defer-datasource-initialization: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all       # 모든 ISR이 ack 응답해야 발행 성공으로 간주
      retries: 3
      properties:
        enable.idempotence: true  # 중복 발행 방지 (PID + Sequence 기반)
    consumer:
      group-id: coffeeshop-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "jpa.basic.coffeeshop.*"

logging:
  level:
    root: info
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace